### ISSUE TITLE
nginx fastgci timeout

### ISSUE THREAD

**Issue by MrUpsidown** [dominikzogg/vagrant-php#13]
fastcgi_read_timeout 600;

**Comment by dominikzogg** [comment]
https://github.com/dominikzogg/vagrant-php/commit/e4a7b4994201fcdd8c75aff35f7c6db0f678cf9d

**Comment by dominikzogg** [comment]
@MrUpsidown after updating your setup (git submodule update --remote) and run vagrant provision within the vagrant-php dir, the problem should be solved
