### ISSUE TITLE
Shutdown Debian 8

### ISSUE THREAD

**Issue by dominikzogg** [dominikzogg/vagrant-php#23]
https://github.com/mitchellh/vagrant/issues/5497

**Comment by dominikzogg** [comment]
https://github.com/boxcutter/debian/issues/16

**Comment by dominikzogg** [comment]
Box shutdown works, but it does not turn off.

**Comment by bitprocessor** [comment]
https://github.com/mitchellh/vagrant/pull/6315 should be fixing the issue (tested on debian/jessie64 box)

**Comment by dominikzogg** [comment]
@bitprocessor so after this PR gets merged and vagrant will be released in a new version it should be fixed, or do i have to change something?

**Comment by bitprocessor** [comment]
@dominikzogg should be fixed, without the need of doing anything else ; you can already fix it yourself, just remove the debian8 folder (see pull request for details)

**Comment by dominikzogg** [comment]
@bitprocessor thanks for the response
