### ISSUE TITLE
what is with multiple submodules?!

### ISSUE THREAD

**Issue by dominikzogg** [dominikzogg/vagrant-php#26]

**Comment by dominikzogg** [comment]
http://stackoverflow.com/questions/16728866/git-submodule-update-specific-submodule-only

**Comment by dominikzogg** [comment]
https://github.com/dominikzogg/vagrant-php/commit/4fdc55b303de7a9c3b8ae0085311c957ee954cdf
https://github.com/dominikzogg/vagrant-php/commit/2a2ea935f361a2af78831f047c71b773e970bfea

@maximkott can you take a look to this too?

**Comment by maximkott** [comment]
I have given it a thought and think it's not an issue after all, it's just the way it is and you have to be aware of it.

**Comment by dominikzogg** [comment]
@maximkott my changes within documentation should solve what you mentioned, not?
