### ISSUE TITLE
outputpuffering: reset to the var at the beginning

### ISSUE THREAD

**Issue by dominikzogg** [dominikzogg/vagrant-php#27]
https://github.com/dominikzogg/vagrant-php/blob/v1-ubuntu/ansible/ansible-on-guest.sh#L18

**Comment by dominikzogg** [comment]
https://github.com/dominikzogg/vagrant-php/commit/3620de7ef006cf55d7aa67c096533367d0db6dde
https://github.com/dominikzogg/vagrant-php/commit/b4d657df3bad3ef74ac14d8145063758f6b7857b

@maximkott can you take a look at this?

**Comment by maximkott** [comment]
I'll check this out tomorrow.

**Comment by dominikzogg** [comment]
@maximkott any news on this?

**Comment by maximkott** [comment]
I think this should work. You can try it out by checking the value of `PYTHONUNBUFFERED`after your was executed. It should be back to normal.

**Comment by dominikzogg** [comment]
@maximkott ok i solved it by not exporting it
