### ISSUE TITLE
Explain Windows User which sharetype to choose

### ISSUE THREAD

**Issue by dominikzogg** [dominikzogg/vagrant-php#39]

**Comment by dominikzogg** [comment]
winnfs is very slow in write operations, but faster in read than vboxfs

**Comment by mikemeier** [comment]
+1 ;D

**Comment by dominikzogg** [comment]
@mikemeier i added more documentation and suggestion to the documentation: https://github.com/dominikzogg/vagrant-php/blob/v1-ubuntu/doc/installation/windows.md
