### ISSUE TITLE
SSH Key Forwarding

### ISSUE THREAD

**Issue by mikemeier** [dominikzogg/vagrant-php#40]
Should that feature work or can it be enabled somehow?

**Comment by dominikzogg** [comment]
@mikemeier yes, it should work, the following line is responsible for this: https://github.com/dominikzogg/vagrant-php/blob/v1-ubuntu/Vagrantfile#L42

**Comment by dominikzogg** [comment]
do you use it with the bash coming from the git installer, and use it keys for forwarning?
https://github.com/dominikzogg/vagrant-php/blob/v1-ubuntu/doc/installation/windows.md#usage

**Comment by dominikzogg** [comment]
@mikemeier any news on this
